#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) readonly buffer LeftInput
{
    float values[];
}
leftInput;

layout(binding = 1) readonly buffer RightInput
{
    float values[];
}
rightInput;

layout(binding = 2) writeonly buffer Output
{
    float values[];
}
outputData;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index < outputData.values.length())
    {
        outputData.values[index] = leftInput.values[index] + rightInput.values[index];
    }
}
