add_executable(atlas_vulkan_example main.cpp)
target_link_libraries(atlas_vulkan_example PRIVATE Atlas::Atlas)
target_compile_features(atlas_vulkan_example PRIVATE cxx_std_20)
target_compile_definitions(atlas_vulkan_example PRIVATE ATLAS_VECTOR_ADD_SPIRV_PATH="${ATLAS_VECTOR_ADD_SPIRV}")
add_dependencies(atlas_vulkan_example atlas_vector_add_shader)
atlas_set_project_warnings(atlas_vulkan_example)
atlas_enable_sanitizers(atlas_vulkan_example)
atlas_enable_clang_tidy(atlas_vulkan_example)
